apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault  
  labels:
    app: nfs-vault
  namespace: vault
spec:
  storageClassName: ""
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  mountOptions: 
    - hard   
    - nfsvers=4.2
  nfs:
    path: "/vault"
    server: nfs-server.nfs.svc.cluster.local
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vault
  labels:
    app: nfs-vault
  namespace: vault
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-vault
